### PR TITLE
AP-6446 rename properties from process-simulation-info-export.default…

### PR DESCRIPTION
**Pull request by shapon2004**
…-max-process-instances to   qbp.maxAllowedProcesses and required changes

### CODE REVIEW

**Review by Janite — COMMENTED** [review]
Should this be merged into the release/v8.4 branch instead of development?

**Comment by shapon2004** [comment]
> 

No, But it will be merged into development and release 8.4.1 ( another new branch )

**Comment by Janite** [comment]
> > 
> 
> No, But it will be merged into development and release 8.4.1 ( another new branch )

In that case, the changes should be made to the development branch of ApromoreEE. The development branch of ApromoreCore is no longer being used.

**Comment by shapon2004** [comment]
will make another PR

**Pull request closed without merging**
