### PR TITLE
Standardising the checkstyle configuration to the root project, so all modules can share a single template

### PR DESCRIPTION
**Pull request by lahiru-maha**
Moving the checkstyle template from the submodules into the root project, so
1.  There is one standard template
2. it can be shared by all submodules
3. template can be imported into development IDEs

### CODE REVIEW

**Review by franklma — APPROVED** [review]
works as expected

**Review by raboczi — APPROVED** [review]
Looks good, makes sense, and minimal.

**Review by raboczi — CHANGES_REQUESTED** [review]
I tried building ApromoreEE/development against ApromoreCore/dev/standardising-checkstyle and the :Apromore-Custom-Plugins:Process-Simulation-Info-Logic:checkstyleMain task failed.  Can you confirm whether this also happens for you?

**Review by raboczi — APPROVED** [review]
Looks like I had an older commit; now everything builds correctly.  Approved!

**Pull request merged**
